name: 'Mothership Core'
description: 'AI agents that build your features'
branding:
  icon: 'zap'
  color: 'purple'
inputs:
  version:
    description: 'Mothership version tag or SHA'
    required: false
    default: 'main'
  mode:
    description: 'Mode to run (plan, build, test, review, status, onboard)'
    required: true
    default: 'build'
  max-iterations:
    description: 'Maximum iterations for loop modes'
    required: false
    default: '10'
  ai-tool:
    description: 'AI CLI tool to use'
    required: false
    default: 'auto'
runs:
  using: 'composite'
  steps:
    - run: |
        VERSION="${{ inputs.version }}"
        # Download mothership.sh if not present
        if [ ! -f mothership.sh ]; then
          curl -fsSL "https://raw.githubusercontent.com/chriscarterux/Mothership---Core/${VERSION}/mothership.sh" -o mothership.sh
          chmod +x mothership.sh
        fi
        AI_TOOL="${{ inputs.ai-tool }}" ./mothership.sh ${{ inputs.mode }} ${{ inputs.max-iterations }}
      shell: bash
